# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acpt_cube <- function(f, Ng, Nt, Ns) {
    .Call('_mstcar_acpt_cube', PACKAGE = 'mstcar', f, Ng, Nt, Ns)
}

acpt_vec <- function(f, Ng) {
    .Call('_mstcar_acpt_vec', PACKAGE = 'mstcar', f, Ng)
}

acceptance_ratio_cube <- function(mod, file_suff, burn) {
    .Call('_mstcar_acceptance_ratio_cube', PACKAGE = 'mstcar', mod, file_suff, burn)
}

acceptance_ratio_mat <- function(mod, file_suff, burn) {
    .Call('_mstcar_acceptance_ratio_mat', PACKAGE = 'mstcar', mod, file_suff, burn)
}

adaptive_variance_theta <- function(gamma, new_theta, s, Ng, Nt, Ns) {
    invisible(.Call('_mstcar_adaptive_variance_theta', PACKAGE = 'mstcar', gamma, new_theta, s, Ng, Nt, Ns))
}

adaptive_variance_rho <- function(delta, new_rho, s, Ng) {
    invisible(.Call('_mstcar_adaptive_variance_rho', PACKAGE = 'mstcar', delta, new_rho, s, Ng))
}

update_theta <- function(theta, Y, n, tau2, beta, z, gamma, Ng, Nt, Ns, method) {
    invisible(.Call('_mstcar_update_theta', PACKAGE = 'mstcar', theta, Y, n, tau2, beta, z, gamma, Ng, Nt, Ns, method))
}

update_beta <- function(beta, theta, tau2, z, Sig_b_i, eta, Ng, Nt, Ns) {
    invisible(.Call('_mstcar_update_beta', PACKAGE = 'mstcar', beta, theta, tau2, z, Sig_b_i, eta, Ng, Nt, Ns))
}

update_tau2 <- function(tau2, theta, beta, z, at, bt, Ng, Nt, Ns) {
    invisible(.Call('_mstcar_update_tau2', PACKAGE = 'mstcar', tau2, theta, beta, z, at, bt, Ng, Nt, Ns))
}

update_Gt_i <- function(Gt_i, z, rho, G, nu, bt, Ng, Nt, Ns, I, neigh, num) {
    invisible(.Call('_mstcar_update_Gt_i', PACKAGE = 'mstcar', Gt_i, z, rho, G, nu, bt, Ng, Nt, Ns, I, neigh, num))
}

update_G <- function(G, Gt_i, nu, nu_0, G0_i, Ng, Nt) {
    invisible(.Call('_mstcar_update_G', PACKAGE = 'mstcar', G, Gt_i, nu, nu_0, G0_i, Ng, Nt))
}

update_z <- function(z, Gt_i, rho, tau2, theta, beta, Ng, Nt, Ns, neigh, num) {
    invisible(.Call('_mstcar_update_z', PACKAGE = 'mstcar', z, Gt_i, rho, tau2, theta, beta, Ng, Nt, Ns, neigh, num))
}

update_rho <- function(rho, Gt_i, z, a_rho, b_rho, delta, Ng, Nt, Ns, I, neigh, num) {
    invisible(.Call('_mstcar_update_rho', PACKAGE = 'mstcar', rho, Gt_i, z, a_rho, b_rho, delta, Ng, Nt, Ns, I, neigh, num))
}

progress <- function(s, n_iter, n, l) {
    invisible(.Call('_mstcar_progress', PACKAGE = 'mstcar', s, n_iter, n, l))
}

gibbs_sampler <- function(mod, n_iter, n_loop = 0L, l = 0L) {
    invisible(.Call('_mstcar_gibbs_sampler', PACKAGE = 'mstcar', mod, n_iter, n_loop, l))
}

get_outname <- function(name, dir, param, iter) {
    .Call('_mstcar_get_outname', PACKAGE = 'mstcar', name, dir, param, iter)
}

output_cube <- function(mod, param, burn, thin, file_suff) {
    .Call('_mstcar_output_cube', PACKAGE = 'mstcar', mod, param, burn, thin, file_suff)
}

output_mat <- function(mod, param, burn, thin, file_suff) {
    .Call('_mstcar_output_mat', PACKAGE = 'mstcar', mod, param, burn, thin, file_suff)
}

get_output <- function(mod, burn, thin, params, file_suff) {
    .Call('_mstcar_get_output', PACKAGE = 'mstcar', mod, burn, thin, params, file_suff)
}

mat2vec <- function(m) {
    .Call('_mstcar_mat2vec', PACKAGE = 'mstcar', m)
}

vec2mat <- function(v, Ng, Nt) {
    .Call('_mstcar_vec2mat', PACKAGE = 'mstcar', v, Ng, Nt)
}

Sig_eta_i <- function(Gt_i, rho, Nt) {
    .Call('_mstcar_Sig_eta_i', PACKAGE = 'mstcar', Gt_i, rho, Nt)
}

sym_test <- function(A, param) {
    invisible(.Call('_mstcar_sym_test', PACKAGE = 'mstcar', A, param))
}

